### ISSUE TITLE
autogen.sh error

### ISSUE THREAD

**Issue by bermond** [dyne/frei0r#11]
I'm getting an error when running `autogen.sh` to compile frei0r plugins. The output is big and I have attached.

The `configure` file is _not_ generated.
Running `autoreconf -si` also produces error.

System information:
**OS:** Arch Linux x86_64
**frei0r-plugins:** git master (currently at 1.6.0.r0.g07ba37c)
**autoconf:** 2.69
**autoconf-archive:** 2017.03.21
**automake:** 1.14
**Compiler:** gcc 6.3.1
**glibc:** 2.25
**OpenCV:** 3.2.0
**Gavl:** 1.4.0
**Cairo:** 1.14.8

Steps to reproduce:
```
$ git clone https://github.com/dyne/frei0r.git frei0r-plugins-git
$ cd frei0r-plugins-git
$ ./autogen.sh
```

[frei0r-plugins-autogen-error.txt](https://github.com/dyne/frei0r/files/870065/frei0r-plugins-autogen-error.txt)

**Comment by ddennedy** [comment]
A quick reading of the log shows the obvious problem:
Makefile.am: error: required file './README' not found

Sadly, this was reported before and not corrected in the release tarball including the one made yesterday:
https://lists.dyne.org/lurker/message/20161019.211825.823012d0.en.html

To make matters even worse, README in git was renamed README.md, and overnight this broke all of MLT's nightly builds in one fell swoop:
http://build.mltframework.org/overview.html

The workaround is simple: create or `touch README`. Also, the fix is simple:
http://stackoverflow.com/questions/15013672/use-autotools-with-readme-md

**Comment by bermond** [comment]
It is working now.
Thank you for the quick reply and fix.

Just a little remark: the final output of `configure` is showing frei0r-plugins 1.5.0 instead of 1.6.0 (or 1.6.0-4-g9da182c). I do not want to open another issue just for this small detail. :)
