### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by frdbr** [dyne/frei0r#124]
There are some commits in Master that Kdenlive needs for alpha rendering. Would it possible to have a new release?

**Comment by ddennedy** [comment]
I would like to get this project to the point that almost nothing needs to be done manually to make a new release to make it easier for other project members to do it:

1. Remove the ChangeLog and just let people see the git history.
2. Do not make tarballs with a pre-generated configure script.
3. Change https://files.dyne.org/frei0r/ to redirect to GitHub releases.

Simply update the version in `CMakeLists.txt` and `configure.ac`, tag git, and add a GitHub release with its auto-generated source archives.

**Comment by jaromil** [comment]
@ddennedy Sounds reasonable for rolling release distros, less for others. But the approach doesn't excludes the current: we can have the automations you mention in place via github actions and have an '-edge' release series as well the current stable one. Would that be ok?

**Comment by ddennedy** [comment]
I am not talking about having automated builds or unstable vs. stable builds. I do not want to make very frequent releases. I am simply talking about the release process. If you do not mind personally making at least one release a year (assuming there are meaningful changes) then keep it the way it is. While I can help make releases, I cannot update the web site. But also, in order to provide this help, I do not want the burdens of manual steps that are essentially redundant.

**Comment by jlskuz** [comment]
Soft bump on this. As @frdbr said some of the latest commits are important for us downstream (Kdenlive) and it would be good if distros package them. If I we can help somehow to make a release happen, just let me.

**Comment by jaromil** [comment]
I guess doing a new release is easier than planning a change in release cycle now. I can take care of that this week.

**Comment by jlskuz** [comment]
Okay, that would be great, thanks!!!

**Comment by jaromil** [comment]
@ddennedy good point about collective access to the website.

I have moved the current one over here in the `gh_pages` branch as-is so you have write access.

**Comment by jaromil** [comment]
Done https://files.dyne.org/frei0r/

also sent a mail to the list
