### ISSUE TITLE
consolidate build-systems

### ISSUE THREAD

**Issue by umlaeute** [dyne/frei0r#125]
as of #95 , i think it's clear that having to maintain two (complex) build-systems is a chore and error prone.
iirc, there's hasn't been a release in almost 5 years that had a non-broken `autotools` setup.

i therefore suggest to just remove the build system you do not like.

**Comment by jaromil** [comment]
@umlaeute hi! yes there are glitches. but before removing, do we have an overview of distro packages and which build system they use?

**Comment by jaromil** [comment]
BTW many thanks for maintaining frei0r in debian!!

in lack of an impact assessment I am wary of removing autoconf, but I am happy to read you have no problems switching to cmake, please do so if that makes you more comfortable, most people seem to already prefer that.

the autotools setup on release 1.8.0 has a change and a bug:
1. we changed the way we ship tarballs since the configure script is not already generated
2. I left a bug by deleting an obsolete TODO file, which is fixed in the latest commit [ee21d09](https://github.com/dyne/frei0r/commit/ee21d097b3cab27202aa15ecec785462dbde25ff)

**Comment by SonnyWalkman** [comment]
Maybe consolidate to meson and ninja like gstreamer has gone to? frei02 has plugins in the gstreamer-bad-plugins repo.

**Comment by jaromil** [comment]
Considering #114 I believe the way to consolidate is to keep cmake and perhaps just that, as also @ddennedy proposed already.

**Comment by jaromil** [comment]
This is now done as soon as I'll merge #142 and tag 2.0 release, an announcement will follow.

If we like to stay in touch more regularly we have an on-topic channel on t.me/frei0r
